rear_left_leg
i2c, 1, 14, 15,
i2c servo, lower-leg,           9,  60, -1, -120,  45, -100
i2c servo, shoulder-forward,   10,  90, +1, -45,  45,  45
i2c servo, shoulder-out,       11, 120, -1, -20,  20,  0
